# Generated by Django 4.2.1 on 2023-06-20 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('FIO', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Manager_shop',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('FIO', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FN', 'Finance'), ('ED', 'Education')], max_length=2)),
                ('work_address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
