# Generated by Django 4.2.1 on 2023-06-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_manager_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager_shop',
            new_name='ShopManager',
        ),
    ]
